{% set name = "Remotery" %}
{% set organization = "Celtoys" %}
{% set version = "1.2.1" %}
{% set sha256 = "5740532229fe4da8d8ab8e310cc6a38d3f198f59314f5ecf1a072aca25f91709" %}

package:
   name: {{ name|lower }}-split

source:
  url: https://github.com/{{ organization }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-build-Add-a-CMake-setup.patch
    - 0002-build-Do-not-treat-compiler-warnings-as-errors-for-n.patch
    - 0003-build-Use-Remotery_static-as-name-for-the-static-lib.patch

build:
  number: 0

outputs:
  - name: {{ name|lower }}
    version: {{ version }}
    script: build_remotery.sh   # [unix]
    script: build_remotery.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]

    test:
      commands:
        # Unix installation tests
        - test -d ${PREFIX}/include/remotery  # [unix]
        - test -f ${PREFIX}/include/remotery/Remotery.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryConfigVersion.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryTargets.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryTargets-release.cmake  # [unix]
        - test -e ${PREFIX}/lib/libRemotery${SHLIB_EXT}  # [unix]

        # API Version tests
        {% set version_split = version.split('.') %}
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_MAJOR {{ version_split[0] }}"  # [unix]
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_MINOR {{ version_split[1] }}"  # [unix]
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_PATCH {{ version_split[2] }}"  # [unix]

        # Prefixed shared libraries must also be present as shared links.
        - test -L ${PREFIX}/lib/libRemotery${SHLIB_EXT}.{{ version_split[0] }}  # [unix]
        - test -L ${PREFIX}/lib/libRemotery${SHLIB_EXT}.{{ version }}  # [unix]

        # Windows installation tests
        - if not exist %LIBRARY_PREFIX%\include\remotery\Remotery.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\Remotery\RemoteryConfig.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\Remotery\RemoteryConfigVersion.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\bin\Remotery.dll (exit 1)  # [win]


outputs:
  - name: {{ name|lower }}-static
    version: {{ version }}
    script: build_remotery.sh   # [unix]
    script: build_remotery.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja  # [win]

    test:
      commands:
        # Unix installation tests
        - test -d ${PREFIX}/include/remotery  # [unix]
        - test -f ${PREFIX}/include/remotery/Remotery.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryConfig.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryConfigVersion.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryTargets.cmake  # [unix]
        - test -f ${PREFIX}/lib/cmake/Remotery/RemoteryTargets-release.cmake  # [unix]
        - test -e ${PREFIX}/lib/libRemotery.a  # [unix]

        # API Version tests
        {% set version_split = version.split('.') %}
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_MAJOR {{ version_split[0] }}"  # [unix]
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_MINOR {{ version_split[1] }}"  # [unix]
        - cat $PREFIX/include/remotery/Remotery.h | grep "RMT_VERSION_PATCH {{ version_split[2] }}"  # [unix]

        # Windows installation tests
        - if not exist %LIBRARY_PREFIX%\include\remotery\Remotery.h (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\Remotery\RemoteryConfig.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\Remotery\RemoteryConfigVersion.cmake (exit 1)  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\Remotery_static.lib (exit 1)  # [win]

about:
  home: https://github.com/{{ organization }}/{{ name }}/
  summary: 'Single C file, Realtime CPU/GPU Profiler with Remote Web Viewer'
  description: |
    A realtime CPU/GPU profiler hosted in a single C file with a viewer that runs in a web browser.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/{{ organization }}/{{ name }}/

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
